name: cp_dio_client
description: A DioClient class for making HTTP requests.
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
